[#5] [UI] As a user, I can sign in with email and password
ducbm051291/surveys-ic pull request #43
Opened 2022-11-17 06:29 UTC by ducbm051291

#5 

## What happened

- As a user, after seeing a Splash Screen, the user will navigate to Login Screen

## Insight

- Create LoginView
- Update Route
- Add Neuzei fonts
- Update Localizable strings
- Layout UI of LoginView
- Create PrimaryButton
- Create PlaceholderModifier
- Create String+Empty extension
- Create Color+Application extension
- Create Font+Neuzei application
 
## Proof Of Work

<img src=https://user-images.githubusercontent.com/24598204/202372657-9f54f108-16c7-4046-8d9d-f11e33840878.png width=400>

2022-11-17 10:54 UTC, blyscuit reviewed
Looks good, few comments

2022-11-17 10:54 UTC, blyscuit commented on Surveys/Sources/Presentation/Modules/LoginView/LoginView.swift
> +    private func setupComponents() -> some View {
You have 2 spellings of `set up`. Please use the same spelling throughout (this should be `setUp`).

2022-11-17 10:54 UTC, blyscuit commented on Surveys/Sources/Supports/Extensions/SwiftUI/Font+Neuzei.swift
> +        case regular = 17.0
Why are the comment numbers and the actual number not the same?

2022-11-17 10:54 UTC, blyscuit commented on Surveys/Sources/Presentation/Views/Modifier/ErrorModifier.swift
> +                .textInputAutocapitalization(.never)
We don't use this modifier with Textfield, not sure if we need to include these.

2022-11-18 00:49 UTC, ducbm051291 commented on Surveys/Sources/Presentation/Modules/LoginView/LoginView.swift
> +    private func setupComponents() -> some View {
Nice catch

2022-11-18 00:50 UTC, ducbm051291 commented on Surveys/Sources/Supports/Extensions/SwiftUI/Font+Neuzei.swift
> +        case regular = 17.0
Good one, it's because I copied and pasted :'(

2022-11-18 02:22 UTC, blyscuit requested changes

2022-11-18 02:22 UTC, blyscuit commented on Surveys/Sources/Supports/Extensions/SwiftUI/Font+Neuzei.swift
> +    }
Please check these names, the name should be from running
```
        for family in UIFont.familyNames.sorted() {
            let names = UIFont.fontNames(forFamilyName: family)
            print("Family: \(family) Font names: \(names)")
        }
```
<img width="919" alt="Screen Shot 2022-11-18 at 09 20 35" src="https://user-images.githubusercontent.com/6356137/202601991-3ce27782-a011-4277-b498-21caa75d20e4.png">

2022-11-18 09:45 UTC, Shayokh144 commented
@ducbm051291 according to  [figma](https://www.figma.com/file/GjRPOjDyZ6f4EDL3wKarRK/Challenge---Mobile-App?node-id=31%3A195&t=QOWcsX7Jf1tDomLe-0) height of button and textfields are same, but in POW it looks different, can you check?

2022-11-18 09:48 UTC, ducbm051291 commented
> @ducbm051291 according to [figma](https://www.figma.com/file/GjRPOjDyZ6f4EDL3wKarRK/Challenge---Mobile-App?node-id=31%3A195&t=QOWcsX7Jf1tDomLe-0) height of button and textfields are same, but in POW it looks different, can you check?

It's 56.0 as design 

<img width="439" alt="Screenshot 2022-11-18 at 16 47 51" src="https://user-images.githubusercontent.com/24598204/202672376-ff3ea99c-b7ea-4097-b099-dd0365ef9e6b.png">

2022-11-18 09:50 UTC, ducbm051291 commented
> @ducbm051291 according to [figma](https://www.figma.com/file/GjRPOjDyZ6f4EDL3wKarRK/Challenge---Mobile-App?node-id=31%3A195&t=QOWcsX7Jf1tDomLe-0) height of button and textfields are same, but in POW it looks different, can you check?

Wow, you're right, let me recheck this. Thanks

2022-11-18 10:00 UTC, Shayokh144 commented on Surveys/Resources/Localization/Localizable.strings
> +"login.loginButton.title" = "Login";
In figma the text is `Log in`, please update

2022-11-18 10:11 UTC, Shayokh144 commented on Surveys/Sources/Supports/Extensions/SwiftUI/Color+Application.swift
> +extension Color {
Can we use `Rswift's R.color` to manage color assets?

2022-11-21 02:34 UTC, blyscuit approved these changes

2022-11-21 02:35 UTC, blyscuit commented
Please look at Taher's comments, rest look good.

2022-11-21 04:02 UTC, merged